CREATE DATABASE terrydb;

CREATE TABLE users(
  id INT UNSIGNED AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL,
  brithday DATE ,
  PRIMARY KEY(id)
)DEFAULT CHARSET=utf8;

SELECT * FROM users;

INSERT INTO users() VALUES();